import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"container mx-auto"}>
        <section className={"w-full"}>
          <div className={'flex justify-center'}>
            <h1 className={"text-6xl font-medium text-white"}>Mon <span className={"uppercase text-prim-amber"}>Route</span></h1>

          </div>
        </section>
      </main>

    </div>
  )
}
